---
- name: "Ensure container is running ({{ container_name }})"
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: started
    interactive: yes
  delegate_to: localhost
  become: yes