---
- name: build image ({{ image_name }}) from dockerfile ({{ docker_filename }})
  docker_image:
    name: "{{ image_name }}"
    build:
      path: "{{ container_path }}/"
      dockerfile: "{{ container_path }}/{{ docker_filename }}"
      pull: yes
    source: build
    state: present
  delegate_to: localhost

- name: ensure container is running, container name ({{ container_name }})
  docker_container:
    state: started
    name: "{{ container_name }}"
    image: "{{ image_name }}"
  delegate_to: localhost